Settings As screen:
    Fill: =RGBA(153, 207, 236, 1)

    "GallerySectionAndModule As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =varGallerySAM
        Fill: =RGBA(202, 202, 202, 1)
        Items: ='Section And Module'
        Layout: =Layout.Vertical
        OnSelect: =ResetForm(FormSectionAndModule);EditForm(FormSectionAndModule)
        TemplateFill: =If(ThisItem.IsSelected,ColorFade(RGBA(98, 100, 167, 1),-2%),RGBA(0, 0, 0, 0))
        TemplatePadding: =0
        TemplateSize: =Min(104, Self.Height - 60)
        Visible: =varSectionAndModule
        Width: =334
        X: =585
        Y: =103
        ZIndex: =1

        Title5 As label:
            Height: =51
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Section
            VerticalAlign: =VerticalAlign.Top
            Width: =196
            X: =27
            Y: =31
            ZIndex: =1

        Subtitle5 As label:
            Height: =54
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Module No'
            VerticalAlign: =VerticalAlign.Top
            Width: =75
            X: =182
            Y: =31
            ZIndex: =2

        Separator5 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =4

        Icon12 As icon.Trash:
            Height: =35
            Icon: =Icon.Trash
            OnSelect: =Remove('Section And Module',ThisItem)
            Width: =35
            X: =245
            Y: =31
            ZIndex: =5

    Label1_22 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        DisabledFill: =RGBA(141, 198, 63, 1)
        Fill: =RGBA(0, 134, 208, 1)
        FontWeight: =FontWeight.Bold
        Height: =67
        Size: =18
        Text: ="SETTINGS"
        Visible: =varTabSelected 
        Width: =1364
        X: =2
        Y: =26
        ZIndex: =2

    Icon1_9 As icon.Home:
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Icon: =Icon.Home
        OnSelect: =Navigate('Main Page')
        Width: =37
        X: =9
        Y: =40
        ZIndex: =3

    Icon2_8 As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Icon: =Icon.BackArrow
        OnSelect: =Navigate('Main Page')
        Width: =37
        X: =60
        Y: =40
        ZIndex: =4

    Image1_15 As image:
        Height: =44
        Image: ='mas-holdings-logo-2ACA338CD6-seeklogo.com'
        RadiusTopLeft: =5
        Width: =226
        X: =860
        Y: =40
        ZIndex: =6

    Label2_30 As label:
        Align: =Align.Right
        Color: =RGBA(179, 179, 179, 1)
        FontWeight: =FontWeight.Bold
        Height: =31
        Size: =16
        Text: ="ACTIVE Linea Intimo - IE"
        Width: =270
        X: =1050
        Y: =53
        ZIndex: =7

    Label2_32 As label:
        Align: =Align.Right
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =37
        Text: ="IE DIGITALIZATION"
        Visible: =varTabSelected
        Width: =180
        X: =1160
        Y: =720
        ZIndex: =8

    Label2_31 As label:
        Align: =Align.Right
        FontWeight: =FontWeight.Semibold
        Height: =37
        Size: =12
        Text: ="Designed by "
        Visible: =varTabSelected 
        X: =1193
        Y: =698
        ZIndex: =9

    Icon5_10 As icon.CancelBadge:
        Color: =RGBA(255, 255, 255, 1)
        Icon: =Icon.CancelBadge
        OnSelect: =Exit()
        Width: =37
        X: =1325
        Y: =30
        ZIndex: =10

    Icon11 As icon.Person:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        Height: =166
        Icon: =Icon.Person
        OnSelect: |-
            =If(
                LookUp('IE Department Name list',User().Email='Email IE','Responsible for STW'.Value) = "STW",
                Set(varAdminButton1,true),
                Set(varAdminAccess,"You don't have permission to access Admin section !!!") And
                Set(varAdminMsg,true)
            )  
            
            //Set(varAdminButton1,true)
        Width: =139
        X: =72
        Y: =140
        ZIndex: =11

    Label10 As label:
        Align: =Align.Center
        DisplayMode: =DisplayMode.View
        FontWeight: =FontWeight.Bold
        Height: =45
        Size: =20
        Text: ="Admin"
        Width: =139
        X: =72
        Y: =325
        ZIndex: =12

    Button9 As button:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Bold
        Height: =137
        OnSelect: |-
            =Set(varStyle,false);
            Set(varSectionAndModule,true)
        Size: =20
        Text: ="Section And Module"
        Visible: =varAdminButton1
        Width: =139
        X: =72
        Y: =415
        ZIndex: =13

    FormSectionAndModule As form:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        DataSource: ='Section And Module'
        Fill: =RGBA(202, 202, 202, 1)
        Height: =575
        Item: =GallerySectionAndModule.Selected
        NumberOfColumns: =1
        OnFailure: =Notify("Form does not submit",NotificationType.Error)
        OnSuccess: =Notify("You Have Succussfully entered data",NotificationType.Success);
        Visible: =varSectionAndModule
        Width: =406
        X: =934
        Y: =103
        ZIndex: =14

        Section_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="Section"
            Default: =ThisItem.Section
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Section And Module'],DataSourceInfo.DisplayName,"Section")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Section And Module'], DataSourceInfo.MaxLength, "Section")
            Required: =false
            Update: =DataCardValue27.Text
            Width: =405
            X: =0
            Y: =0
            ZIndex: =15

            DataCardKey23 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue27 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey23.Y + DataCardKey23.Height + 5
                ZIndex: =2

            ErrorMessage27 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue27.Y + DataCardValue27.Height
                ZIndex: =3

            StarVisible20 As label:
                Align: =Align.Center
                Height: =DataCardKey23.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey23.Y
                ZIndex: =4

        "'Module No_DataCard1' As typedDataCard.textualEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="ModuleNo"
            Default: =ThisItem.'Module No'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Section And Module'],DataSourceInfo.DisplayName,"ModuleNo")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Section And Module'], DataSourceInfo.MaxLength, "ModuleNo")
            Required: =false
            Update: =DataCardValue28.Text
            Width: =405
            X: =0
            Y: =1
            ZIndex: =15

            DataCardKey24 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue28 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey24.Y + DataCardKey24.Height + 5
                ZIndex: =2

            ErrorMessage28 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue28.Y + DataCardValue28.Height
                ZIndex: =3

            StarVisible23 As label:
                Align: =Align.Center
                Height: =DataCardKey24.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey24.Y
                ZIndex: =4

    Button9_1 As button:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Bold
        Height: =137
        OnSelect: |-
            =Set(varSectionAndModule,false);
            Set(varStyle,true)
        Size: =20
        Text: ="Style"
        Visible: =varAdminButton1
        Width: =139
        X: =234
        Y: =415
        ZIndex: =17

    Group13 As group:
        Height: =5
        Width: =5
        X: =80
        Y: =80
        ZIndex: =17

        Button10 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: |-
                =ResetForm(FormSectionAndModule);NewForm(FormSectionAndModule);Set(varGallerySAM,Blank());Set(varGallerySAM,{});
                Refresh('Section And Module')
            Text: ="Add"
            Visible: =varSectionAndModule
            X: =970
            Y: =400
            ZIndex: =15

        Button10_1 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: |-
                =SubmitForm(FormSectionAndModule);
                Refresh('Section And Module')
            Text: ="Update"
            Visible: =varSectionAndModule
            X: =1147
            Y: =400
            ZIndex: =16

    "GalleryStyle As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =varGalleryST
        Fill: =RGBA(202, 202, 202, 1)
        Items: ='Lockup Details'
        Layout: =Layout.Vertical
        OnSelect: =ResetForm(FormStyle);EditForm(FormStyle)
        TemplateFill: =If(ThisItem.IsSelected,ColorFade(RGBA(98, 100, 167, 1),-2%),RGBA(0, 0, 0, 0))
        TemplatePadding: =0
        TemplateSize: =Min(104, Self.Height - 60)
        Visible: =varStyle
        Width: =334
        X: =585
        Y: =103
        ZIndex: =18

        Title5_1 As label:
            Height: =51
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Style
            VerticalAlign: =VerticalAlign.Top
            Width: =196
            X: =27
            Y: =31
            ZIndex: =1

        Separator5_1 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =4

        Icon12_1 As icon.Trash:
            Height: =35
            Icon: =Icon.Trash
            OnSelect: =Remove('Lockup Details',ThisItem)
            Width: =35
            X: =245
            Y: =31
            ZIndex: =5

    FormStyle As form:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        DataSource: ='Lockup Details'
        Fill: =RGBA(202, 202, 202, 1)
        Height: =575
        Item: =GalleryStyle.Selected
        NumberOfColumns: =1
        OnFailure: =Notify("Form does not submit",NotificationType.Error)
        OnSuccess: =Notify("You Have Succussfully entered data",NotificationType.Success);
        Visible: =varStyle
        Width: =406
        X: =934
        Y: =103
        ZIndex: =19

        Style_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="Style"
            Default: =ThisItem.Style
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Lockup Details'],DataSourceInfo.DisplayName,"Style")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Lockup Details'], DataSourceInfo.MaxLength, "Style")
            Required: =false
            Update: =DataCardValue31.Text
            Width: =405
            X: =0
            Y: =0
            ZIndex: =20

            DataCardKey27 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue31 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey27.Y + DataCardKey27.Height + 5
                ZIndex: =2

            ErrorMessage31 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue31.Y + DataCardValue31.Height
                ZIndex: =3

            StarVisible26 As label:
                Align: =Align.Center
                Height: =DataCardKey27.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey27.Y
                ZIndex: =4

    Label13 As label:
        Fill: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Semibold
        Height: =60
        Size: =15
        Text: =varAdminAccess
        Visible: =varAdminMsg
        Width: =534
        X: =72
        Y: =618
        ZIndex: =22

    Group13_1 As group:
        Height: =5
        Width: =5
        X: =20
        Y: =20
        ZIndex: =22

        Button10_2 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: =ResetForm(FormStyle);NewForm(FormStyle);Set(varGalleryST,Blank());Set(varGalleryST,{});Refresh('Lockup Details')
            Text: ="Add"
            Visible: =varStyle
            X: =970
            Y: =400
            ZIndex: =20

        Button10_3 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: =SubmitForm(FormStyle);Refresh('Lockup Details')
            Text: ="Update"
            Visible: =varStyle
            X: =1147
            Y: =400
            ZIndex: =21

